# -*- coding: utf-8 -*-
"""Final_Assignment_Answers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1MWbuOXOC5etsL_jyX-jnhXvTAAZ37G
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

url = "https://raw.githubusercontent.com/Priya-tops/Tops-Assessment-Data/main/Data%20Analytics/finance_economics_dataset.csv"
df = pd.read_csv(url)
df.head()

df.shape

df.info()

df['Stock Index'].nunique()

df['Date'] = pd.to_datetime(df['Date'])
(df['Date'].min(), df['Date'].max())

df.isnull().sum()

(df.select_dtypes(include=np.number) < 0).sum()

df['GDP Growth (%)'].describe()

df[df['Trading Volume'] <= 0]

df.duplicated().sum()

sns.boxplot(data=df[['GDP Growth (%)','Gold Price (USD per Ounce)','Crude Oil Price (USD per Barrel)']])
plt.show()

df['Inflation Rate (%)'].describe()

df['Unemployment Rate (%)'].mean()

df.groupby('Stock Index')['Trading Volume'].sum().idxmax()

df['Stock Index'].value_counts()

df[['Inflation Rate (%)','Interest Rate (%)']].corr()

df['Consumer Confidence Index'].mean()

df.std(numeric_only=True).idxmax()

df['Gold Price (USD per Ounce)'].max()

df.loc[df['Crude Oil Price (USD per Barrel)'].idxmax(), 'Date']

df['Corporate Profits (Billion USD)'].mean()

"""## 🛒 Retail Analysis"""

url2 = "https://raw.githubusercontent.com/Priya-tops/Tops-Assessment-Data/main/Data%20Analytics/Retail%20Data.csv"
df2 = pd.read_csv(url2)
df2.head()

df2['Order Date'] = pd.to_datetime(df2['Order Date'], dayfirst=True)
df2['Ship Date'] = pd.to_datetime(df2['Ship Date'], dayfirst=True)

df2['Sales'] = df2['Order Total'].replace('[$,]', '', regex=True).astype(float)
df2['Profit'] = df2['Profit Margin'].replace('[$,]', '', regex=True).astype(float)
df2['Shipping Cost'] = df2['Shipping Cost'].replace('[$,]', '', regex=True).astype(float)

df2['Shipping Days'] = (df2['Ship Date'] - df2['Order Date']).dt.days

df2.info()

df2.shape

df2.duplicated().sum()

df2.isnull().sum()

df2[df2['Ship Date'] < df2['Order Date']]

df2['Customer Type'].unique()
df2['Order Priority'].unique()

df2['Ship Mode'].value_counts()

df2['City'].value_counts().head()

(df2['Order Quantity'].min(), df2['Order Quantity'].max())

df2[(df2['Sales'] <= 0) | (df2['Order Quantity'] <= 0)]

(df2['Discount %'] != df2['Discount $']).sum()

(df2['Sales'] - df2['Profit']).head()

df2.groupby('Product Name')['Order Quantity'].sum().sort_values(ascending=False).head()

df2.groupby('Account Manager')['Sales'].sum().idxmax()

df2.groupby('Ship Mode')['Shipping Cost'].mean()

df2.groupby('Product Name')['Profit'].sum().idxmax()

df2.groupby('Product Name')['Profit'].sum().idxmax()

